FROM node:14.15.1-alpine AS node

# Arguments
ARG TYPEORM_CONNECTION
ARG TYPEORM_HOST
ARG TYPEORM_USERNAME
ARG TYPEORM_PASSWORD
ARG TYPEORM_DATABASE
ARG TYPEORM_PORT
ARG TYPEORM_SYNCHRONIZE
ARG TYPEORM_LOGGING
ARG TYPEORM_ENTITIES
ARG TYPEORM_MIGRATIONS
ARG DISCORD_BOT_TOKEN
ARG DISCORD_BOT_PREFIX

# Environment Variables from Arguments
ENV TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
ENV TYPEORM_HOST=${TYPEORM_HOST}
ENV TYPEORM_USERNAME=${TYPEORM_USERNAME}
ENV TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
ENV TYPEORM_DATABASE=${TYPEORM_DATABASE}
ENV TYPEORM_PORT=${TYPEORM_PORT}
ENV TYPEORM_SYNCHRONIZE=${TYPEORM_SYNCHRONIZE}
ENV TYPEORM_LOGGING=${TYPEORM_LOGGING}
ENV TYPEORM_ENTITIES=${TYPEORM_ENTITIES}
ENV TYPEORM_MIGRATIONS=${TYPEORM_MIGRATIONS}
ENV DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
ENV DISCORD_BOT_PREFIX=${DISCORD_BOT_PREFIX}


# Build
FROM node AS build
WORKDIR /app
COPY package*.json ./
RUN npm i
COPY . .
RUN npm run build

# Final
FROM node AS final
RUN mkdir -p /app/dist
WORKDIR /app
COPY package*.json ./
RUN npm i --only=production
COPY  --from=build /app/dist ./dist

EXPOSE 4000
ENTRYPOINT ["node", "./dist/server.js"]