version: '3.3'

services:
  db:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
      PGDATA: /data/postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ../database/data:/data/postgres
    networks:
      solarbot_net:
        aliases:
          - solarbot_net_db

networks:
  portainer:
    external: true
  solarbot_net:
    external: false
